### ISSUE TITLE
Forecast Error

### ISSUE THREAD

**Issue by trevisanfelipe** [jinglescode/demos#1]
I did the test with the same scenario and with the symbol BTCUSD see the results:

Ticker Symbol: MSFT

Train: https://prnt.sc/ppotmz
Predict: https://prnt.sc/ppotrq
Predict Result: https://prnt.sc/ppou1p

Ticker Symbol: BTCUSD (Looks like you couldn't train properly)

Predict: https://prnt.sc/ppov1v
Predict Result: https://prnt.sc/ppov38

Thanks a lot if you can help me.

**Comment by jinglescode** [comment]
1. base on this [screenshot](https://prnt.sc/ppov1v), I would increase the "training dataset size" to maybe 90% or 95% or 98%. because a large part of the data before mid-2017 is relatively low (compared to those after)
2. feel free to use to other time series forecasting techniques, as this is a simple moving average
